### ISSUE TITLE
Spam to the console.

### ISSUE THREAD

**Issue by Sky-Evil** [LuckPerms/ExtraContexts#38] opened 2021-09-25 13:00 UTC
I have the Terra plugin installed for additional worlds. I made a mining world. But Every time my player is in this world. The console fills up with an error (screenshot). Removing the ExtraContexts plugin removes this error, but I need this plugin, can you fix it?

WARN]: [LuckPerms] An exception was thrown by me.lucko.extracontexts.calculators.WorldGuardFlagCalculator whilst calculating the context of subject CraftPlayer{name=

![tsQtcOd5dfA](https://user-images.githubusercontent.com/39336712/134772466-929c47b1-3544-499e-80ae-9a511dc9a241.jpg)

**Comment by Laarryy** [comment] 2021-10-19 01:37
Are these the only errors that appear, even in the `logs/latest.log` file?

**Comment by Laarryy** [comment] 2021-10-19 01:38
This seems to be a duplicate of #34 - closing for now, you can follow there for updates 
Edit: can't close this manually, due to permissions snafu. Will do as soon as I can

**Closed as completed** 2021-10-20 03:19 UTC
